<div class="organisation-feed <?= $wrapperClass; ?>" data-feed-id="<?= $feedId; ?>" data-organisation-id="<?= $organisationId ?? ''; ?>" data-parent="<?= $parent ?? ''; ?>">
  <?= $this->render('components/atoms/messaging/loader/loader.phtml', ['wrapperClass' => 'js-loader']) ?>
</div>

<?php
$js = <<<JS
$(document).ready(function() {
  var initOrganisationFeed = function initOrganisationFeed() {
    var params = {
      id: '{$feedId}'
    };

    var feed = finna.organisationFeed();

    feed.init($('.{$wrapperClass}'), finna.organisationInfo);
    feed.loadFeed(params);
  };
  
  if(!finna.organisationFeed || !finna.organisationInfo) {
    return;
  }

  initOrganisationFeed();
});
JS;

echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET');
?>
