<div class="organisation-feed <?= $wrapperClass; ?>">
  <?= $this->render('components/atoms/messaging/loader/loader.phtml', ['wrapperClass' => 'js-loader']) ?>
</div>

<?php
$js = <<<JS
$(document).ready(function() {
  if(!finna.organisationFeed) {
    return;
  }

  finna.organisationFeed.init($('.{$wrapperClass}'), { id: '{$feedId}'})
});
JS;

echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET');
?>
