<div class="keywords">
  <div class="keywords-error-wrapper js-keywords-error hidden">
    <?= $this->render('components/01-molecules/02-messaging/00-error-alert.phtml', ['alert' => $submitError]) ?>
  </div>
  <div class="keywords-spinner js-spinner hidden">
    <i class="fa fa-spinner fa-spin" aria-hidden="true"></i>
  </div>
  <div class="keywords-wrapper js-keywords-wrapper">
    <?php if (isset($editable) && $editable) : ?>
      <button class="keywords-toggle-button btn js-toggle-keywords" aria-label="<?= $toggleButtonLabel; ?>">
        <span class="keywords-toggle-label"><?= $addKeyword ?></span>
        <i class="fa fa-tag keywords-toggle-icon" aria-hidden="true"></i>
      </button>
      <div class="keywords-controls js-controls">
        <?= $this->render(
          'components/01-molecules/02-messaging/in-testing-alert/in-testing-alert.phtml',
          ['alert' => $alert]
        ); ?>
        <?= $this->render('components/01-molecules/00-forms/add-keyword.phtml', ['label' => $form['label'], 'submit' => $form['submit'], 'errorMessage' => $form['error']]); ?>
      </div>
    <?php endif; ?>
    <div class="keywords-current js-current">
      <?php if (isset($editable) && $editable) : ?>
        <p class="keywords-current-text">
          <?= $currentKeywords ?>
          (<span class="js-keywords-counter"><?= count($tags) ?></span>):
        </p>
      <?php endif; ?>
      <div class="keywords-current-list js-keywords-list">
        <?php foreach ($tags as $tag) : ?>
          <button data-keyword-id="<?= urlencode($tag); ?>" class="btn keyword js-keyword">
            <span class="keyword-button-text">
              <?= $tag; ?>
            </span>
            <i class="fa fa-times keyword-button-icon" aria-hidden="true"></i>
          </button>
        <?php endforeach; ?>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    finna.keywords.init();
  });
</script>
