<form class="add-keyword-form form-group js-add-keyword" novalidate>
  <label for="keyword" class="add-keyword-form-label"><?= $label; ?></label>
  <div class="add-keyword-form-input-wrapper">
    <input class="add-keyword-form-input form-control" type="text" name="keyword" id="keyword" aria-required="true" required />
    <button type="submit" class="btn btn-primary add-keyword-form-button">
      <?= $submit; ?>
    </button>
  </div>
  <div class="add-keyword-form-error">
    <?= $errorMessage; ?>
  </div>
</form>
