<?php
$widget = $target == 'widget';
?>

<div class="js-schedule-widget schedule-widget organisation-info<?= $showDetails ? ' with-details' : '' ?><?= $widget ? ' organisation-info-widget' : '' ?>" data-parent="<?= $parent; ?>" data-target="<?= $target; ?>" data-id="<?= $id; ?>">
  <?php if ($widget) : ?>
    <h2>Heading</h2>
    <div class="loader js-loader">
      <?= $this->render('components/molecules/messaging/loader/loader.phtml'); ?>
    </div>
    <div class="js-content hide">
      <div class="<?= $showDetails ? 'info-col ' : ''; ?>info">
        <div class="organisation-wrapper">
          <div class="organisation-dropdown-holder">
            <?= $this->render('components/molecules/navigation/dropdowns/sort.phtml', ['items' => [], 'label' => 'Select library', 'dropdownClass' => 'organisation js-organisation-menu']) ?>
          </div>
          <div class="js-is-open">
            <span class="js-open is-open open js-info-element">
              <?= $open; ?>
            </span>
            <span class="js-closed is-open closed js-info-element">
              <?= $closed; ?>
            </span>
          </div>
        </div>
      <?php endif; ?>
      <div class="schedules info">
        <div class="js-week-navigation week-navigation week-navi-holder">
          <button class="week-navigation-control js-prev-week" data-dir="-1">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            <span class="sr-only">Previous week</span>
          </button>
          <span>
            <?= $week; ?> <span class="js-week-number"></span>
          </span>
          <button class="week-navigation-control js-next-week" data-dir="+1">
            <i class="fa fa-arrow-right" aria-hidden="true"></i>
            <span class="sr-only">Next week</span>
          </button>
        </div>
        <div class="loader js-loader">
          <?= $this->render('components/molecules/messaging/loader/loader.phtml'); ?>
        </div>
        <div class="js-content">
          <div class="js-opening-times-week opening-times-week"></div>
        </div>
        <div class="js-no-schedules js-info-element">
          <?= $notAvailable; ?>
        </div>
        <div class="js-mobile-schedules mobile-schedules info-element js-info-element"></div>
      </div>
      <div class="js-schedules-info schedules-info js-info-element">
        <p><?= $schedulesInfo; ?></p>
      </div>
      <?php if ($widget && $showDetails) : ?>
      </div>
      <div class="details-col">
        <a href="" data-href="<?= $organisationHomeUrl; ?>">
          <img src="<?= $organisationPlaceholderImage; ?>" alt="" class="js-facility-image facility-image" />
        </a>
        <div class="details-wrapper">
          <div>
            <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn js-info-element js-email'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-at' aria-hidden='true'></i><span class='sr-only'>Email</span>", 'content' => "<a href='mailto:test.test@test.fi'>test.test@test.fi</a>"]) ?>
            <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn js-info-element js-phone'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-phone-square' aria-hidden='true'></i><span class='sr-only'>Phone</span>", 'content' => "<a href='tel:1234567'>1234567</a>"]) ?>
            <a href="https://opas.matka.fi/?to=Linnankatu%202,%20Turku" target="_blank" class="js-route js-info-element btn">
              <i class="fa fa-bus" aria-hidden="true"></i>
              <span class="sr-only">Reittiohjeet</span>
            </a>
          </div>
          <a href="<?= $organisationHomeUrl; ?>" target="_blank" class="js-facebook js-info-element btn">
            <i class="fa fa-facebook-square" aria-hidden="true"></i>
            <span class="sr-only">Facebook</span>
          </a>
          <div class="js-map map js-info-element">
            <a href="https://www.google.com/maps?q=Linnankatu+2+Turku" target="_blank">
              <i class="fa fa-map-marker" aria-hidden="true">
              </i>
              <span class="js-map-address">Linnankatu 2, 20100 Keskusta (Turku)</span>
            </a>
          </div>
          <div class="js-details-link js-info-element">
            <a href="" data-href="<?= $organisationHomeUrl; ?>">
              <i class="fa fa-home" aria-hidden="true"></i>
              Palvelupisteen tiedot
            </a>
          </div>
          <div class="js-services services">
            <button class="btn btn-round js-service-wifi js-info-element">
              <i class="fa fa-wifi" aria-hidden="true"></i>
              <span class="sr-only">Langaton verkko</span>
            </button>
            <button class="btn btn-round js-service-print js-info-element">
              <i class="fa fa-print" aria-hidden="true"></i>
              <span class="sr-only">Tulostin</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  <?php endif; ?>
</div>

<template class="js-time-row-template">
  <div class="time-row">
    <div class="cell date">
      <span class="js-date"></span>
    </div>
    <div class="cell description">
      <span class="js-name"></span>
      <span class="js-staff name-staff">
        <?= $staffAvailable; ?>
      </span>
      <span class="info js-info"></span>
      <span class="js-selfservice selfservice-only hide">
        <?= $selfService; ?>
      </span>
    </div>
    <div class="cell time-container js-time-container"></div>
  </div>
</template>

<template class="js-time-template">
  <div class="time-template">
    <span class="js-period">
      <span class="js-opens"></span> - <span class="js-closes"></span>
    </span>
    <span class="js-closed closed-today hide">
      <?= $closed; ?>
    </span>
  </div>
</template>

<template class="js-mobile-schedule-link-template">
  <a href="#" target="_blank">
    Template link
  </a>
</template>

<script type="text/javascript">
  $(document).ready(function onReady() {
    var service = finna.organisationInfo;

    finna.weekSchedule.init($('.js-schedule-widget'), service);

    finna.weekSchedule.loadOrganisationList();

    setTimeout(function() {
      finna.weekSchedule.showDetails('<?= $id; ?>', '', true);
    }, 1000)
  })
</script>
