<?php
$widget = $target == 'widget';
?>

<div class="organisation-info" data-parent="<?= $id; ?>" data-target="<?= $target; ?>">
  <?php if ($widget) : ?>
    <div>
      <h2>Heading</h2>
    </div>
    <div>
      <?= $this->render('components/molecules/messaging/loader/loader.phtml'); ?>
    </div>
    <div class="content hide">
      <div class="<?= $showDetails ? 'info-col ' : ''; ?>info">
        <div class="organisation-dropdown-holder">
          <?= $this->render('components/molecules/navigation/dropdowns/sort.phtml', ['items' => [], 'label' => 'Select library']) ?>
        </div>
        <span class="js-is-open js-open is-open open info-element">
          <?= $open; ?>
        </span>
        <span class="js-is-open js-closed is-open closed info-element">
          <?= $closed; ?>
        </span>
      <?php endif; ?>
      <div class="info schedules">
        <div class="week-navi-holder">
          <i class="fa fa-arrow-left prev-week js-week-navigate" data-dir="-1"></i>
          <?= $week; ?> <span class="js-week-number"></span>
          <i class="fa fa-arrow-right next-week js-week-navigate" data-dir="+1"></i>
        </div>
        <div class="loader js-loader">
          <?= $this->render('components/molecules/messaging/loader/loader.phtml'); ?>
        </div>
        <div class="content">
          <div class="js-opening-times-week opening-times-week">
            <div class="day-container"></div>
          </div>
        </div>
        <div class="js-no-schedules info-element">
          <?= $notAvailable; ?>
        </div>
        <div class="js-mobile-schedules mobile-schedules info-element"></div>
      </div>
      <div class="js-schedules-info schedules-info info-element">
        <p><?= $schedulesInfo; ?></p>
      </div>
      <?php if ($widget && $showDetails) : ?>
      </div>
      <div class="details details-col">
        <a href="#" data-href="<?= $organisationHomeUrl; ?>" class="facility details">
          <img src="<?= $organisationPlaceholderImage; ?>" alt="" class="js-facility-image" />
        </a>
        <div class="contact-links">
          <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn btn-open-widget info-element js-email'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-at'><span class='sr-only'>Email</span></i>", 'content' => "<ul><dl><a href='mailto:test.test@test.fi'>test.test@test.fi</a></dl></li>"]) ?>

          <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn btn-open-widget info-element js-phone'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-phone-square'><span class='sr-only'>Phone</span></i>", 'content' => "<ul><dl><a href='mailto:test.test@test.fi'>test.test@test.fi</a></dl></li>"]) ?>

          <a href="https://opas.matka.fi/?to=Linnankatu%202,%20Turku" target="_blank" class="js-route info-element">
            <span class="btn">
              <i class="fa fa-bus"></i>
              <span class="sr-only">Reittiohjeet</span>
            </span>
          </a>

          <a href="<?= $organisationHomeUrl; ?>">
            <span class="btn">
              <i class="fa fa-bus"></i>
              <span class="sr-only">Reittiohjeet</span>
            </span>
          </a>

          <a href="<?= $organisationHomeUrl; ?>" target="_blank" class="js-facebook info-element">
            <span class="btn">
              <i class="fa fa-facebook-square"></i>
              <span class="sr-only">Facebook</span>
            </span>
          </a>
        </div>

        <div class="js-map map info-element">
          <a href="https://www.google.com/maps?q=Linnankatu+2+Turku" target="_blank">
            <i class="fa fa-map-marker">
            </i>
            <span class="js-map-address">Linnankatu 2, 20100 Keskusta (Turku)</span>
          </a>
        </div>

        <div class="js-details-link info-element">
          <a href="#" data-href="<?= $organisationHomeUrl; ?>" class="details">
            <i class="fa fa-home"></i>
            Palvelupisteen tiedot
          </a>
        </div>

        <div class="js-services services">
          <span class="btn btn-open-widget btn-round js-service-wifi info-element" title="Langaton verkko">
            <i class="fa fa-wifi"></i>
            <span class="sr-only">Langaton verkko</span>
          </span>
          <span class="btn btn-open-widget btn-round js-service-print info-element" title="Tulostin">
            <i class="fa fa-print"></i>
            <span class="sr-only">Tulostin</span>
          </span>
        </div>
      </div>
    </div>
  <?php endif; ?>
</div>
<template class="js-time-row-template">
  <div class="cell js-date"></div>
  <div class="cell description">
    <span class="js-name"></span>
    <span class="js-staff">
      <?= $staffAvailable; ?>
    </span>
    <span class="info js-info"></span>
    <span class="js-selfservice hide">
      <?= $selfService; ?>
    </span>
  </div>
  <div class="cell js-time-container"></div>
</template>

<template class="js-time-template">
  <span class="js-period">
    <span class="js-opens"></span> - <span class="js-closes"></span>
  </span>
  <span class="js-closed hide">
    <?= $closed; ?>
  </span>
</template>

<template class="js-mobile-schedule-link-template">
  <a href="#" target="_blank">
    Template link
  </a>
</template>
