<div class="services">
  <h5 class="service-header">Service List</h5>
  <ul class="service-list">
    <li class="service-list-item">
      <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn', 'btn-link'], 'buttonText' => '3D-tulostin', 'content' => "<h4>3D-tulostin</h4><p>3D-tulostinta voi käyttää uutistorilla. Ajanvaraus <a href='https://varaamo.turku.fi' rel='nofollow noreferrer noopener' target='_blank'>Varaamosta</a></p>", 'position' =>
      'bottom']); ?>
    </li>
    <li class="service-list-item">
      <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn', 'btn-link'], 'buttonText' => 'Digitointilaite', 'content' => "<h4>Digitointilaite</h4>Musiikkiosastolla on mahdollista digitoida VHS-kasetteja, LP-levyjä, C-kasetteja, dioja ja kuvia.", 'position' => 'bottom']); ?>
    </li>
    <li class="service-list-item">
      <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn', 'btn-link'], 'buttonText' => 'Elektroninen suurennuslaite', 'content' => "<h4>Elektroninen suurennuslaite</h4>Uutistorilla", 'position' => 'bottom']); ?>
    </li>
    <li class="service-list-item">
      <span>Kirkasvalolamppu</span>
    </li>
    <li class="service-list-item">
      <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn', 'btn-link'], 'buttonText' => 'Kopiokone, tulostin ja skanneri', 'content' => "<h4>Kopiokone, tulostin ja skanneri</h4>Uutistorilla on väritulostin, kopiokone ja skanneri. Tieto-osastolla on mustavalkotulostin", 'position' => 'bottom']); ?>
    </li>
    <li class="service-list-item">
      <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn', 'btn-link'], 'buttonText' => 'Mikrokortin/-filmin lukulaite', 'content' => "<h4>Mikrokortin/-filmin lukulaite</h4><p>Tieto-osastolla. Lukulaitteen ajanvaraus <a href='https://varaamo.turku.fi' rel='nofollow noreferrer noopener' target='_blank'>Varaamosta</a></p>", 'position' => 'bottom']); ?>
    </li>
    <li class="service-list-item">
      <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn', 'btn-link'], 'buttonText' => 'Mobiililaitteiden lataus', 'content' => "<h4>Mobiililaitteiden lataus</h4>Uutistorilla ja tieto-osastolla", 'position' => 'bottom']); ?>
    </li>
    <li class="service-list-item">
      <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn', 'btn-link'], 'buttonText' => 'Tietokoneet', 'content' => "<h4>Tietokoneet</h4><p><a href='http://www.eb2.dpg.fi/vaski/' rel='nofollow noreferrer noopener' target='_blank'>eBooking</a></p>", 'position' => 'bottom']); ?>
    </li>
  </ul>
</div>
