<div class="feed-tabs" id="feed-tabs-<?= $tablistId; ?>">
  <div class="tabs-responsive">
    <div class="visible-md visible-lg">
      <div class="feed-tabs-container">
        <h2 class="feed-tabs-title"><?= $tablistLabel; ?></h2>
        <?= $this->render('components/01-molecules/01-navigation/_tabs.phtml', ['label' => $tablistLabel, 'tabs' => $tabs]); ?>
      </div>
    </div>
  </div>
  <div class="feed-accordions" role="tablist">
    <h2 class="feed-accordions-title"><?= $tablistLabel; ?></h2>
    <?php foreach ($tabs as $tab) : ?>
      <div class="accordion <?= isset($tab['active']) && $tab['active'] ? 'active initial-active' : ''; ?>" aria-selected="<?= isset($tab['active']) && $tab['active'] ? 'true' : 'false'; ?>" role="tab" data-tab="<?= $tab['id']; ?>">
        <span class="title"><?= $tab['name']; ?></span>
        <i class="icon"></i>
      </div>
    <?php endforeach; ?>
  </div>
  <div class="tab-content" id="tab-content-<?= $tablistId; ?>">
    <div class="feed-container" data-init="0">
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    finna.feedTabs.init("feed-tabs-<?= $tablistId; ?>");
  });
</script>
