<?php
$showForm = isset($showSearchForm) && $showSearchForm;
?>

<div class="service-points <?= $wrapperClass ?? ''; ?>" data-organisation-id="<?= $organisationId; ?>">
  <?php if (isset($widgetHeading)) : ?>
    <h2><?= $widgetHeading; ?></h2>
  <?php endif; ?>
  <p class="consortium-notification hide"></p>
  <div class="service-points-control-bar">
    <div class="form-wrapper<?= !$showForm ? ' hidden' : ''; ?>">
      <?= $this->render('components/molecules/forms/search/search.phtml', ['label' => $formLabel, 'wrapperClass' => 'js-service-points-form', 'placeholder' => $formPlaceholder]) ?>
      <p class="notification hide"><?= $locationNotAvailableText; ?></p>
      <div class="autocomplete-container"></div>
    </div>
    <div class="map-controls">
      <button type="button" class="map-control-show btn btn-primary js-show-map"><?= $showMapButton; ?></button>
      <div class="map-controls-wrapper hidden js-map-controls">
        <button type="button" class="map-control js-center"><?= $centerButton; ?></button>
        <button type="button" class="map-control js-show-all hidden"><?= $showAllButton; ?></button>
      </div>
    </div>
  </div>
  <div class="office map hidden js-map-holder" aria-hidden="true">
    <div id="<?= $widgetClass . '-' . $organisationId ?>" class="map-widget <?= $widgetClass ?? ''; ?>"></div>
    <div class="js-marker-tooltip hide"></div>
  </div>
  <div class="service-point-info">
    <div class="service-point">
      <h3 class="service-point-title">Turun pääkirjasto</h3>
      <p class="service-point-address">
        Linnankatu 2, 20100 Keskusta (Turku)
      </p>
      <div class="service-point-links">
        <a href="#" target="_blank" class="service-point-link">
          <i class="fa fa-bus"></i> Directions
        </a>
        <a href="" class="service-point-link">
          <i class="fa fa-desktop"></i> Reserve a computer
        </a>
        <a href="#" target="_blank" class="service-point-link">
          <i class="fa fa-home"></i> Homepage
        </a>
      </div>
      <p class="service-point-email">
        <i class="fa fa-envelope"></i>
        <span>kaupunginkirjasto(at)turku.fi</span>
      </p>
    </div>
    <div class="service-point-opening-times">
      <h3 class="opening-times-title">
        <span class="open">Open</span>
        <span class="closed">Closed</span>
      </h3>
      <p class="opening-times-today">
        <i class="fa fa-clock-o"></i> Open today
        <span class="opens">9</span> - <span class="closes">20</span>
      </p>
      <p class="opening-times-staff-availabel">
        Staff available
        <span class="opens">10</span> - <span class="closes">19</span>
      </p>
    </div>
  </div>
</div>

<template class="js-map-bubble">
  <div class="map-bubble">
    <h5 class="name js-name"></h5>
    <p class="js-address"></p>
  </div>
</template>
<template class="js-attribution">
  <i class="fa fa-map-marker marker open"></i>
  <span class="map-marker-text"><?= $markerOpenText; ?></span>
  <i class="fa fa-map-marker marker closed"></i>
  <span class="map-marker-text"><?= $markerClosedText; ?></span>
  <i class="fa fa-map-marker marker no-schedule"></i>
  <span class="map-marker-text"><?= $markerNotAvailableText; ?></span>
  <span class="js-expand-map expand expand-map map-marker-text marker">
    <i class="fa fa-expand"></i><?= $markerExpandText; ?>
  </span>
  <span class="js-contract-map contract-map map-marker-text marker hidden">
    <i class="fa fa-condense"></i>
    <?$markerCollapseText;?>
  </span>
</template>
