<?php
$showForm = isset($showSearchForm) && $showSearchForm;
?>

<div class="service-points <?= $wrapperClass ?? ''; ?>" data-organisation-id="<?= $organisationId; ?>" data-parent="<?= $parent; ?>">
  <?php if (isset($widgetHeading)) : ?>
    <h2><?= $widgetHeading; ?></h2>
  <?php endif; ?>
  <p class="consortium-notification hide"></p>
  <div class="service-points-control-bar">
    <div class="form-wrapper<?= !$showForm ? ' hidden' : ''; ?>">
      <?= $this->render('components/molecules/forms/search/search.phtml', ['label' => $formLabel, 'wrapperClass' => 'js-service-points-form', 'placeholder' => $formPlaceholder]) ?>
      <p class="notification hide"><?= $locationNotAvailableText; ?></p>
      <div class="autocomplete-container"></div>
    </div>
    <div class="map-controls">
      <button type="button" class="map-control-show btn btn-primary js-show-map"><?= $showMapButton; ?></button>
      <div class="map-controls-wrapper hidden js-map-controls">
        <button type="button" class="map-control js-center"><?= $centerButton; ?></button>
        <button type="button" class="map-control js-show-all hidden"><?= $showAllButton; ?></button>
      </div>
    </div>
  </div>
  <div class="office map hidden js-map-holder" aria-hidden="true">
    <div id="<?= $widgetClass . '-' . $organisationId ?>" class="map-widget <?= $widgetClass ?? ''; ?>"></div>
    <div class="js-marker-tooltip hide"></div>
  </div>
  <?= $this->render('components/molecules/info-block/service-point/service-point-info.phtml', ['directionsText' => $directionsText, 'homepageText' => $homepageText, 'openText' => $openText, 'closedText' => $closedText, 'openTodayText' => $openTodayText, 'staffAvailableText' => $staffAvailableText, 'wrapperClass' => $infoWrapperClass]) ?>
</div>

<template class="js-map-bubble">
  <div class="map-bubble">
    <h5 class="name js-name"></h5>
    <p class="js-address"></p>
  </div>
</template>
<template class="js-attribution">
  <i class="fa fa-map-marker marker open"></i>
  <span class="map-marker-text"><?= $openText; ?></span>
  <i class="fa fa-map-marker marker closed"></i>
  <span class="map-marker-text"><?= $closedText; ?></span>
  <i class="fa fa-map-marker marker no-schedule"></i>
  <span class="map-marker-text"><?= $notAvailableText; ?></span>
  <span class="js-expand-map expand expand-map map-marker-text marker">
    <i class="fa fa-expand"></i><?= $expandText; ?>
  </span>
  <span class="js-contract-map contract-map map-marker-text marker hidden">
    <i class="fa fa-condense"></i>
    <?$markerCollapseText;?>
  </span>
</template>
