<div>
  <?= $this->render('components/molecules/lists/service/service.phtml', ['title' => $title, 'listWrapperClass' => $listWrapperClass, 'items' => $staticItems]); ?>
</div>
<script type="text/javascript">
  $(document).ready(function onDocumentReady() {
    var $holder = $('.js-hardware');

    var data = [{
        0: "Digitointilaite",
        shortDesc: "Musiikkiosastolla on mahdollista digitoida VHS-kasetteja, LP-levyjä, C-kasetteja, dioja ja kuvia."
      },
      {
        0: "Elektroninen suurennuslaite",
        shortDesc: "Uutistorilla"
      },
      {
        0: "Kopiokone, tulostin ja skanneri",
        shortDesc: "Uutistorilla on väritulostin, kopiokone ja skanneri. Tieto-osastolla on mustavalkotulostin"
      },
      {
        0: "Mikrokortin/-filmin lukulaite",
        shortDesc: "<p>Tieto-osastolla. Lukulaitteen ajanvaraus <a href=\"https://varaamo.turku.fi\" rel=\"nofollow noreferrer noopener\" target=\"_blank\">Varaamosta</a></p>"
      }
    ];

    if (!initServiceListDemo) {
      return;
    }

    initServiceListDemo($holder, data);
  });
</script>
