<div class="finna-main-tabs <?= isset($menuClass) ? $menuClass : ''; ?>">
  <?= $this->render('components/01-molecules/06-tabs/00-tabs.phtml', ['tablistClass' => 'hidden-xs', 'label' => $label, 'tabs' => $tabs]) ?>

  <div class="mobile-main-tabs visible-xs">
    <?= $this->render('components/01-molecules/01-dropdowns/_sort.phtml', ['labelClass' => 'tab-title', 'label' => $label, 'iconLabel' => $more, 'items' => $tabs]) ?>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function onReady() {
    $tablist = $('.js-pl-example-tabs');

    $tabs = $tablist.find('li[role="tab"]');
    $menuitems = $tablist.find('li[role="menuitem"]');

    $tabs.on('click', function onClickTab() {
      var $this = $(this);

      $tabs.removeClass('active');
      $tabs.attr('aria-selected', false);

      $this.addClass('active');
      $this.attr('aria-selected', true);
    });

    $menuitems.on('click', function onClickMenuitem() {
      var $this = $(this);

      $menuitems.removeClass('active');

      $this.addClass('active');
    })
  });
</script>
