<div>
  <?= $this->render('components/01-molecules/06-tabs/_nav-tabs.phtml', ['label' => $tablistLabel, 'tabs' => $tabs, 'tablistClass' => 'hidden-xs js-pl-example-tabs']) ?>
</div>
<script type="text/javascript">
  $(document).ready(function onReady() {
    $tablist = $('.js-pl-example-tabs');
    $tabs = $tablist.find('li[role="tab"]');

    $tabs.on('click', function onClickTab() {
      var $this = $(this);

      $tabs.removeClass('active');
      $tabs.attr('aria-selected', false);

      $this.addClass('active');
      $this.attr('aria-selected', true);
    });
  });
</script>
