<div class="finna-main-tabs">
  <ul class="nav nav-tabs" role="tablist" aria-label="<?= $tablistLabel; ?>">
    <?php foreach ($tabs as $tab) : ?>
      <li role="tab" id="<?= $tab['id']; ?>-tab" class="<?= isset($tab['active']) && $tab['active'] ? 'active' : ''; ?>" aria-selected="<?= isset($tab['active']) && $tab['active'] ? 'true' : 'false'; ?>">
        <a href="<?= $tab['href']; ?>"><?= $tab['name']; ?></a>
      </li>
    <?php endforeach; ?>
  </ul>
</div>
