<?= $this->render('components/01-molecules/06-tabs/_tabs.phtml', ['label' => $label, 'tabs' => $tabs]) ?>
<script type="text/javascript">
  $(document).ready(function onReady() {
    $tablist = $('ul[role="tablist"]');

    $tabs = $tablist.find('li[role="tab"]');

    $tabs.on('click', function onClickTab() {
      var $this = $(this);

      $tabs.removeClass('active');
      $tabs.attr('aria-selected', false);

      $this.addClass('active');
      $this.attr('aria-selected', true);
    });
  });
</script>
