<div class="finna-main-tabs <?= isset($tablistClass) ? $tablistClass : ''; ?>">
  <ul class="nav nav-tabs hidden-xs" role="tablist" aria-label="<?= $label; ?>">
    <?php foreach ($tabs as $tab) : ?>
      <li role="tab" id="<?= $tab['id']; ?>-tab" class="<?= isset($tab['active']) && $tab['active'] ? 'active' : ''; ?>" aria-selected="<?= isset($tab['active']) && $tab['active'] ? 'true' : 'false'; ?>">
        <a href="<?= $tab['href']; ?>"><?= $tab['name']; ?></a>
      </li>
    <?php endforeach; ?>
  </ul>
  <div class="mobile-main-tabs visible-xs">
    <div class="dropdown">
      <div class="dropdown-toggle" data-toggle="dropdown">
        <span class="tab-title">
          <?= $label; ?>
        </span>
        <span class="more">More <i class="fa fa-arrow-down" aria-hidden="true"></i></span>
      </div>
      <div class="dropdown-menu" role="menu">
        <?php foreach ($tabs as $tab) : ?>
          <li role="menuitem" class="<?= isset($tab['active']) && $tab['active'] ? 'active' : ''; ?>">
            <a href="<?= $tab['href']; ?>"><?= $tab['name']; ?></a>
          </li>
        <?php endforeach; ?>
      </div>
    </div>
  </div>
</div>
