<div class="finna-main-tabs <?= isset($tablistClass) ? $tablistClass : ''; ?>">
  <ul class="nav nav-tabs hidden-xs" role="tablist" aria-label="<?= $label; ?>">
    <?php foreach ($tabs as $tab) : ?>
      <li role="tab" id="<?= $tab['id']; ?>-tab" class="<?= isset($tab['active']) && $tab['active'] ? 'active' : ''; ?>" aria-selected="<?= isset($tab['active']) && $tab['active'] ? 'true' : 'false'; ?>">
        <a href="<?= $tab['href']; ?>"><?= $tab['name']; ?></a>
      </li>
    <?php endforeach; ?>
  </ul>
  <div class="mobile-main-tabs visible-xs">
    <?= $this->render('components/01-molecules/01-dropdowns/_sort.phtml', ['labelClass' => 'tab-title', 'label' => $label, 'iconLabel' => 'More', 'items' => $tabs]) ?>
  </div>
</div>
