<ul class="nav nav-tabs <?= isset($tablistClass) ? $tablistClass : ''; ?>" role="tablist" aria-label="<?= $label; ?>">
  <?php foreach ($tabs as $tab) : ?>
    <li role="tab" id="<?= $tab['id']; ?>-tab" class="<?= isset($tab['active']) && $tab['active'] ? 'active' : ''; ?>" aria-selected="<?= isset($tab['active']) && $tab['active'] ? 'true' : 'false'; ?>">
      <a href="<?= $tab['href']; ?>"><?= $tab['name']; ?></a>

      <?= $this->render('components/01-molecules/05-tooltip/_tooltip.phtml', ['buttonClasses' => ['tooltip'], 'position' => 'bottom', 'content' => $tab['tooltip'], 'buttonText' => '<i class="fa fa-info-big"  aria-hidden="true"></i>']) ?>
    </li>
  <?php endforeach; ?>
</ul>
