<footer class="hidden-print">
  <div class="container">
    <div class="footer-container">
      <?php foreach ($footer['columns'] as $column) : ?>
        <div class="footer-column">
          <h4><strong><?= $column['name'] ?></strong></h4>
          <ul>
            <?php foreach ($column['items'] as $item) : ?>
              <li><a href="#"><?= $item; ?></a></li>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endforeach; ?>
    </div>
    <hr>
    <div class="footer-container">
      <?php foreach ($footer['links'] as $link) : ?>
        <div class="footer-column">
          <a href="#" title="<?= $link['name']; ?>">
            <img src="<?= $link['image']; ?>" alt="">
            <span class="sr-only"><?= $link['name']; ?></span>
          </a>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
</footer>
