<div>
  <?= $this->render('components/molecules/info-block/service-point/service-point-info.phtml', ['wrapperClass' => 'js-service-point-demo', 'directionsText' => $directionsText, 'homepageText' => $homepageText, 'closedText' => $closedText, 'openText' => $openText, 'openTodayText' => $openTodayText, 'staffAvailableText' => $staffAvailableText]); ?>
</div>
<script type="text/javascript">
  $(document).ready(function onDocumentReady() {
    $(document).ready(function onDocumentReady() {
      var id = "85141";

      var settings = {
        target: 'page',
        parent: 'Vaski'
      }

      var service = finna.organisationInfo;

      service.getOrganisations(settings.target, settings.parent, id, {}, function onResponse() {
        finna.servicePointInfo.init($('.js-service-point-demo'), settings, service, id);
      });

    });
  });
</script>
