<?php
$widget = $target == 'widget';
?>

<div class="schedule-widget organisation-info <?= $wrapperClass ?? ''; ?>" data-parent="<?= $parent; ?>" data-target="<?= $target ?? 'page'; ?>" data-id="">
  <?php if ($widget) : ?>
    <?php if (isset($widgetHeading)) : ?>
      <h2><?= $widgetHeading; ?></h2>
    <?php endif; ?>
    <?= $this->render('components/molecules/messaging/loader/loader.phtml', ['wrapperClass' => 'loader js-loader']); ?>
    <div class="js-content hide">
      <div class="<?= (isset($showDetails) && $showDetails) ? 'info-col ' : ''; ?>info">
        <div class="organisation-dropdown-wrapper">
          <div class="organisation-dropdown-holder">
            <?= $this->render('components/molecules/navigation/dropdowns/sort.phtml', ['dropdownClass' => 'organisation js-organisation-menu', 'items' => [], 'label' => $dropdownFallbackLabel ?? '', 'fallbackLabel' => $dropdownFallbackLabel ?? '']) ?>
          </div>
          <div class="js-is-open">
            <span class="js-open is-open open js-info-element">
              <?= $openText ?? ''; ?>
            </span>
            <span class="js-closed is-open closed js-info-element">
              <?= $closedText ?? ''; ?>
            </span>
          </div>
        </div>
      <?php endif; ?>
      <div class="schedules info">
        <?= $this->render('components/molecules/navigation/pagination/pager-with-label.phtml', ['wrapperClass' => 'js-week-navigation week-navigation week-navi-holder', 'prevButton' => ['class' => 'week-navigation-control js-prev-week', 'text' => $previousWeekLabel], 'label' => $weekText . ' <span class="js-week-number"></span>', 'nextButton' => ['class' => 'week-navigation-control js-next-week', 'text' => $nextWeekLabel]]) ?>
        <?= $this->render('components/molecules/messaging/loader/loader.phtml', ['wrapperClass' => 'loader js-loader']); ?>
        <div class="js-content">
          <div class="js-opening-times-week opening-times-week"></div>
        </div>
        <div class="js-no-schedules js-info-element">
          <p><?= $noSchedulesAvailableText; ?></p>
        </div>
        <ul class="js-mobile-schedules mobile-schedules info-element js-info-element"></ul>
      </div>
      <div class="js-schedules-info schedules-info js-info-element">
      </div>
      <?php if ($widget && (isset($showDetails) && $showDetails)) : ?>
      </div>
      <div class="details-col">
        <a href="" data-href="<?= $facilityLink ?? ''; ?>">
          <img src="<?= $facilityPlaceholderImage ?? ''; ?>" alt="" class="js-facility-image facility-image" />
        </a>
        <div class="details-wrapper">
          <div>
            <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn js-info-element js-email'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-at' aria-hidden='true'></i><span class='sr-only'>" . ($emailText ?? '') . "</span>", 'content' => ""]) ?>
            <?= $this->render('components/molecules/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn js-info-element js-phone'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-phone-square' aria-hidden='true'></i><span class='sr-only'>" . ($phoneText ?? '') . "</span>", 'content' => ""]) ?>
            <a href="" target="_blank" class="js-route js-info-element btn">
              <i class="fa fa-bus" aria-hidden="true"></i>
              <span class="sr-only"><?= $directionsText ?? ''; ?></span>
            </a>
          </div>
          <a href="" target="_blank" class="js-facebook js-info-element btn">
            <i class="fa fa-facebook-square" aria-hidden="true"></i>
            <span class="sr-only"><?= $facebookText ?? ''; ?></span>
          </a>
          <div class="js-map map js-info-element">
            <a href="" target="_blank">
              <i class="fa fa-map-marker" aria-hidden="true">
              </i>
              <span class="js-map-address"></span>
            </a>
          </div>
          <div class="js-details-link js-info-element">
            <a href="" data-href="<?= $facilityLink ?? ''; ?>">
              <i class="fa fa-home" aria-hidden="true"></i>
              <?= $servicePointInfoText ?? ''; ?>
            </a>
          </div>
          <div class="js-services services">
            <span class="service-item js-service-wifi js-info-element">
              <i class="fa fa-wifi" aria-hidden="true"></i>
              <span class="sr-only"><?= $wifiText ?? ''; ?></span>
            </span>
            <span class="service-item js-service-print js-info-element">
              <i class="fa fa-print" aria-hidden="true"></i>
              <span class="sr-only"><?= $printText ?? ''; ?></span>
            </span>
          </div>
        </div>
      </div>
    </div>
  <?php endif; ?>
</div>

<template class="js-time-row-template">
  <div class="time-row">
    <div class="cell date">
      <span class="js-date"></span>
    </div>
    <div class="cell description">
      <span class="js-name"></span>
      <span class="js-staff name-staff">
        <?= $staffAvailableText; ?>
      </span>
      <span class="info js-info"></span>
      <span class="js-selfservice selfservice-only hide">
        <?= $selfServiceText; ?>
      </span>
    </div>
    <div class="cell time-container js-time-container"></div>
  </div>
</template>

<template class="js-time-template">
  <div>
    <span class="js-period">
      <span class="js-opens"></span> - <span class="js-closes"></span>
    </span>
    <span class="js-closed closed-today hide">
      <?= $closedText ?? ''; ?>
    </span>
  </div>
</template>
