<div>
  <?= $this->render('components/organisms/map/widget/widget.phtml', ['widgetHeading' => $widgetHeading, 'inputLabel' => $inputLabel, 'formButton' => $formButton, 'locationNotAvailableText' => $locationNotAvailableText, 'showMapButton' => $showMapButton, 'centerButton' => $centerButton, 'showAllButton' => $showAllButton, 'widgetClass' => $widgetClass, 'wrapperClass' => $wrapperClass, 'showSearchForm' => $showSearchForm, 'organisationId' => $organisationId]); ?>
</div>
<script type="text/javascript">
  $(document).ready(function onDocumentReady() {
    if (!initMapWidgetDemo) {
      return;
    }

    initMapWidgetDemo('<?= $wrapperClass; ?>', '<?= $widgetClass ?>');
  });
</script>
