<div>
  <?= $this->render('components/organisms/map/service-points/service-points.phtml', ['widgetHeading' => $widgetHeading, 'formLabel' => $formLabel, 'locationNotAvailableText' => $locationNotAvailableText, 'showMapButton' => $showMapButton, 'centerButton' => $centerButton, 'showAllButton' => $showAllButton, 'widgetClass' => $widgetClass, 'wrapperClass' => $wrapperClass, 'showSearchForm' => $showSearchForm, 'organisationId' => $organisationId, 'openText' => $openText, 'closedText' => $closedText, 'notAvailableText' => $notAvailableText, 'expandText' => $expandText, 'collapseText' => $collapseText, 'formPlaceholder' => $formPlaceholder, 'directionsText' => $directionsText, 'homepageText' => $homepageText, 'openTodayText' => $openTodayText, 'staffAvailableText' => $staffAvailableText, 'infoWrapperClass' => $infoWrapperClass]); ?>
</div>
<script type="text/javascript">
  $(document).ready(function onDocumentReady() {
    var buildings = ["85141", "85968"];
    var organisationList;

    finna.organisationInfo.getOrganisations('page', 'Vaski', buildings.join(","), {}, function onResponse(response) {
      organisationList = response.list;

      buildings.forEach(function getBuildingSchedule(id) {
        finna.organisationInfo.getSchedules('page', 'Vaski', id, '2020-10-05', null, true, true, function callback() {
          return;
        });
      });


      var url = 'http://map-api.finna.fi/v1/rendered/{z}/{x}/{y}.png';

      finna.mapWidget.init($('.<?= $wrapperClass ?>'), $('.<?= $widgetClass; ?>'), url, organisationList, $('.<?= $infoWrapperClass; ?>'));

      finna.mapWidget.draw();
    });


  });
</script>
