<div>
  <?= $this->render('components/organisms/map/service-points/service-points.phtml', ['widgetHeading' => $widgetHeading, 'searchFormLabel' => $searchFormLabel, 'locationNotAvailableText' => $locationNotAvailableText, 'showMapButton' => $showMapButton, 'centerButton' => $centerButton, 'showAllButton' => $showAllButton, 'widgetClass' => $widgetClass, 'wrapperClass' => $wrapperClass, 'showSearchForm' => $showSearchForm, 'preselectOrganisationId' => $preselectOrganisationId, 'openText' => $openText, 'closedText' => $closedText, 'notAvailableText' => $notAvailableText, 'expandText' => $expandText, 'collapseText' => $collapseText, 'searchFormPlaceholder' => $searchFormPlaceholder, 'directionsText' => $directionsText, 'homepageText' => $homepageText, 'openTodayText' => $openTodayText, 'staffAvailableText' => $staffAvailableText, 'infoWrapperClass' => $infoWrapperClass]); ?>
</div>
<script type="text/javascript">
  $(document).ready(function onDocumentReady() {
    var settings = {
      target: 'page',
      parent: 'Vaski',
      buildings: ["85141", "85968"]
    }

    var url = 'http://map-api.finna.fi/v1/rendered/{z}/{x}/{y}.png';

    finna.mapWidget.init($('.<?= $wrapperClass ?>'), $('.<?= $widgetClass; ?>'), $('.<?= $infoWrapperClass; ?>'), url, settings);
  });
</script>
