<div class="finna-multi-level-tabs <?= isset($menuClass) ? $menuClass : ''; ?>">
  <div class="finna-main-tabs">
    <?= $this->render('components/01-molecules/01-navigation/tabs/_tabs.phtml', ['tablistClass' => 'hidden-xs', 'label' => $tablistLabel, 'tabs' => $tabs]) ?>

    <div class="mobile-main-tabs visible-xs">
      <?= $this->render('components/01-molecules/01-navigation/dropdowns/_sort.phtml', ['labelClass' => 'text-left tab-title', 'label' => $tablistLabel, 'iconLabel' => $more, 'items' => $tabs, 'dropdownClass' => 'btn-block', 'fallbackLabel' => $fallbackLabel]) ?>
    </div>
  </div>
  <div class="finna-secondary-tabs">
    <?= $this->render('components/01-molecules/01-navigation/tabs/_tabs-secondary.phtml', ['label' => $secondaryTablistLabel, 'tabs' => $secondaryTabs]) ?>
  </div>
</div>
