<div class="finna-main-tabs">
  <?= $this->render('components/molecules/navigation/tabs/tabs.phtml', ['label' => $label, 'tabs' => $tabs, 'tablistClass' => $tablistClass]) ?>
</div>
<script type="text/javascript">
  $(document).ready(function onTabsReady() {
    var initExampleTabs = function() {
      var isTooltip = <?= json_encode($tooltip); ?>;

      var $tablist = $('.<?= $tablistClass; ?>');
      var $tabs = $tablist.find('li[role="tab"]');

      if (isTooltip) {
        var $tabLinks = $tabs.find('a');

        $tabLinks.on('click', function onClickTab() {
          $tabs.removeClass('active');
          $tabs.attr('aria-selected', false);

          $(this).parent().addClass('active');
          $(this).parent().attr('aria-selected', true);
        });
      } else {
        $tabs.on('click', function onClickTab() {
          $tabs.removeClass('active');
          $tabs.attr('aria-selected', false);

          $(this).addClass('active');
          $(this).attr('aria-selected', true);
        });
      }
    };

    initExampleTabs();
  });
</script>
