<div class="organisation-map <?= $wrapperClass ?? ''; ?>">
  <?php if (isset($widgetHeading)) : ?>
    <h2><?= $widgetHeading; ?></h2>
  <?php endif; ?>
  <p class="consortium-notification hide"></p>
  <div class="organisation-map-control-bar">
    <div class="organisation-map-form-wrapper">
      <form class="organisation-map-form form-inline">
        <div class="input-group">
          <input id="office-search" class="js-office-search form-control" type="text" aria-label="<?= $inputLabel; ?>" placeholder="" aria-placeholder="" />
          <button type="submit" class="btn btn-primary js-office-search-btn">
            <i class="fa fa-search"></i>
            <span class="sr-only"><?= $formButton; ?></span>
          </button>
          <p class="notification hide"><?= $locationNotAvailableText; ?></p>
        </div>
      </form>
      <div class="autocomplete-container"></div>
    </div>
    <div class="organisation-map-controls">
      <button type="button" class="organisation-map-control-show btn btn-primary js-show-map"><?= $showMapButton; ?></button>
      <div class="map-controls hidden js-map-controls">
        <button type="button" class="organisation-map-control js-center"><?= $centerButton; ?></button>
        <button type="button" class="organisation-map-control js-show-all"><?= $showAllButton; ?> all</button>
      </div>
    </div>
  </div>
  <div class="office map hidden js-map-holder" aria-hidden="true">
    <div id="openlayers-canvas" class="map-widget <?= $widgetClass ?? ''; ?>"></div>
    <div id="marker-tooltip" class="hide"></div>
  </div>
</div>
<template class="js-map-bubble">
  <div class="map-bubble">
    <h5 class="name js-name"></h5>
    <p class="js-address"></p>
  </div>
</template>
