<div class="collapse-accordion">
  <button type="button" data-toggle="collapse" data-target="#toggle" class="collapse-accordion-header collapsed" aria-expanded="false" aria-controls="toggle" id="accordionToggle">
    Toggle
  </button>
  <section id="toggle" aria-expanded="false" class="collapse-accordion-panel collapse" aria-labelledby="accordionToggle">
    <p>Content</p>
    <p>Content</p>
  </section>
</div>
