<div class="finna-record-tabs">
  <?= $this->render('components/01-molecules/01-navigation/tabs/_tabs-record.phtml', ['label' => $label, 'tabs' => $tabs, 'tablistClass' => 'js-tablist-records-example']) ?>
</div>
<script type="text/javascript">
  $(document).ready(function onRecordTabsReady() {
    var initExampleRecordTabs = function() {
      var $tablist = $('.js-tablist-records-example');
      var $tabs = $tablist.find('li[role="tab"]');

      $tabs.on('click', function onClickTab() {
        $tabs.removeClass('active');
        $tabs.attr('aria-selected', false);

        $(this).addClass('active');
        $(this).attr('aria-selected', true);
      });
    }

    initExampleRecordTabs();
  });
</script>
