<div class="finna-secondary-tabs">
  <?= $this->render('components/molecules/navigation/tabs/tabs-secondary.phtml', ['tablistClass' => 'js-tablist-secondary-example', 'label' => $label, 'tabs' => $tabs]) ?>
</div>
<script type="text/javascript">
  $(document).ready(function onSecondaryTabsReady() {
    var initExampleSecondaryTabs = function() {
      var $tablist = $('.js-tablist-secondary-example');
      var $tabs = $tablist.find('li[role="tab"]');

      $tabs.on('click', function onClickTab() {
        $tabs.removeClass('active');
        $tabs.attr('aria-selected', false);

        $(this).addClass('active');
        $(this).attr('aria-selected', true);
      });
    }

    initExampleSecondaryTabs();
  });
</script>
