<div class="c-input-container">
  <form class="js-pl-example-textarea-form" novalidate>
    <div class="form-group">
      <?= $this->render('components/atoms/forms/textarea/_textarea.phtml', ['inputName' => $textareaName, 'label' => $labelRequired, 'cols' => '10', 'errorMessage' => $inputError, 'required' => true, 'inputClass' => 'js-pl-input-textarea']) ?>
    </div>
    <button type="submit" class="hidden"><?= $submit; ?></button>
  </form>
</div>
<script type="text/javascript">
  $(document).ready(function onReady() {
    var $form = $('.js-pl-example-textarea-form');
    var $input = $('.js-pl-input-textarea');

    $input.on('blur', function onInputBlur() {
      if (!$form[0].checkValidity()) {
        $input.closest('.form-group').addClass('has-error');
      } else {
        $input.closest('.form-group').removeClass('has-error');
      }
    });

    $form.on('submit', function onSubmit(event) {
      event.preventDefault();
    })
  });
</script>
