<div class="c-input-container">
  <form class="js-pl-example-checkbox-form" novalidate>
    <fieldset class="form-group checkbox">
      <legend class="hidden"><?= $inputCheckboxLabel; ?></legend>
      <?= $this->render('components/00-atoms/05-forms/_checkbox.phtml', ['inputName' => $inputCheckboxName, 'label' => $labelRequired, 'required' => true, 'errorMessage' => $inputCheckboxError, 'inputClass' => 'js-pl-input-checkbox']); ?>
    </fieldset>
    <button type="submit" class="hidden"><?= $submit; ?></button>
  </form>
</div>
<script type="text/javascript">
  $(document).ready(function onReady() {
    var $form = $('.js-pl-example-checkbox-form');
    var $input = $('.js-pl-input-checkbox');

    $input.on('change', function onInputChange() {
      if (!$form[0].checkValidity()) {
        $input.closest('.form-group').addClass('has-error');
      } else {
        $input.closest('.form-group').removeClass('has-error');
      }
    });

    $form.on('submit', function onSubmit(event) {
      event.preventDefault();
    })
  });
</script>
