<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
      <div class="modal-body">
        <?= $loadingText; ?>...
      </div>
    </div>
  </div>
</div>
<div>
  <?= $this->render('components/organisms/feed/organisation/organisation.phtml', ['wrapperClass' => $wrapperClass, 'feedId' => $feedId]) ?>
</div>
