<div class="organisation-info" data-parent="<?= $id; ?>" data-target="<?= $target; ?>">
  <div class="info schedules">
    <div class="week-navi-holder">
      <i class="fa fa-arrow-left prev-week week-navi" data-dir="-1"></i>
      <span class="week-text">
        <?= $week; ?> <span class="num"></span>
      </span>
      <i class="fa fa-arrow-right next-week week-navi" data-dir="+1"></i>
    </div>
    <div class="loader">
      <?= $this->render('components/molecules/messaging/loader/loader.phtml'); ?>
    </div>
    <div class="content">
      <div class="opening-times-week">
        <div class="day-container template hide"></div>
        <div class="time-row template hide">
          <div class="cell date"></div>
          <div class="cell description">
            <span class="name"></span>
            <span class="name-staff">
              <?= $staffAvailable; ?>
            </span>
            <span class="info"></span>
            <span class="selfservice-only hide">
              <?= $selfService; ?>
            </span>
          </div>
          <div class="cell time-container">
            <div class="cell time-template">
              <span class="period">
                <span class="opens"></span> - <span class="closes"></span>
              </span>
              <span class="closed-today hide">
                <?= $closed; ?>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="no-schedules info-element">
      <?= $notAvailable; ?>
    </div>
    <div class="mobile-schedule-link-template hide" aria-hidden="true">
      <a href="#" target="_blank">
        Template link
      </a>
    </div>
    <div class="mobile-schedules info-element"></div>
  </div>
  <div class="schedules-info info-element">
    <p><?= $schedulesInfo; ?></p>
  </div>
</div>
