<!DOCTYPE html>
<html class="<?= $htmlClass ?? '' ?>" lang="en">

<head>
  <title><?= $title ?? '' ?></title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width" />

  <link rel="stylesheet" href="../../styles/style.min.css?<?= $cacheBuster ?>" media="all" />
  <link rel="stylesheet" href="../../styles/patternlab/pattern-scaffolding.css?<?= $cacheBuster ?>" media="all" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/leaflet.css?<?= $cacheBuster ?>" media="all" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mockjax/2.5.1/jquery.mockjax.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/leaflet.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol/dist/L.Control.Locate.min.js" charset="utf-8"></script>

  <script src="../../js/vendor/bootstrap.min.js"></script>
  <script src="../../js/vendor/bootstrap-accessibility.min.js"></script>
  <script src="../../js/vendor/global-vufind-mock.min.js"></script>
  <script type="text/javascript" src="../../js/vendor/mockjax.min.js"></script>
  <script type="text/javascript" src="../../js/main.js"></script>
  <!-- Begin Pattern Lab (Required for Pattern Lab to run properly) -->
  <?= $patternLabHead ?>
  <!-- End Pattern Lab -->
</head>

<body class="<?= $bodyClass ?? '' ?>"></body>

</html>
